version: '1'
services:
  books-backend:
    build: ./books-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    env_file:
      - ./environments/backend.env

  frontend:
    build: ./books-frontend
    ports:
      - "4200:80"
    depends_on:
      - books-backend

  postgres-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: bookechange-db
        POSTGRES_USER: bookexchange_user
        POSTGRES_PASSWORD: password
    volumes: 
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050

  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:latest
    ports:
    - "1080:1080"
    - "1025:1025"